 
        const M = "male";
        const F = "female";
        const studentsInfo= [
          {
            fname: "Taher",
            lname: "Khan",
            class: 5,
            div: "B",
            rollno: 201,
            gender: M,
            favsports: "Cricket",
            house: "Purple",
            bloodgroup: "O+",
            mobile: 948552512,
            city: "Bangalore",
          },
          {
            fname: "Kabir",
            lname: "Singh",
            class: 9,
            div: "C",
            rollno: 501,
            gender: M,
            favsports: "Cricket",
            house: "Green",
            bloodgroup: "O+",
            mobile: 948052512,
            city: "Pune",
          },
          {
            fname: "Umesh",
            lname: "Kulkarni",
            class: 7,
            div: "C",
            rollno: 101,
            gender: M,
            favsports: "Football",
            house: "Purple",
            bloodgroup: "A+",
            mobile: 942412512,
            city: "Bangalore",
          },
          {
            fname: "Kavita",
            lname: "Tiwari",
            class: 10,
            div: "A",
            rollno: 51,
            gender: F,
            favsports: "Cricket",
            house: "Green",
            bloodgroup: "B+",
            mobile: 948552000,
            city: "Belgaum",
          },
          {
            fname: "Trisha",
            lname: "Khanna",
            class: 7,
            div: "C",
            rollno: 53,
            gender: F,
            favsports: "Football",
            house: "Purple",
            bloodgroup: "A+",
            mobile: 948966512,
            city: "Pune",
          },
          {
            fname: "Tahera",
            lname: "Shaikh",
            class: 8,
            div: "C",
            rollno: 510,
            gender: F,
            favsports: "Kabbadi",
            house: "Green",
            bloodgroup: "A-",
            mobile: 948552500,
            city: "Agra",
          },
          {
            fname: "Tiya",
            lname: "Singh",
            class: 9,
            div: "C",
            rollno: 141,
            gender: F,
            favsports: "Football",
            house: "Red",
            bloodgroup: "A-",
            mobile: 94811112,
            city: "Bangalore",
          },
          {
            fname: "Kabir",
            lname: "Kumar",
            class: 8,
            div: "C",
            rollno: 501,
            gender: M,
            favsports: "Cricket",
            house: "Purple",
            bloodgroup: "B+",
            mobile: 9111112512,
            city: "Pune",
          },
          {
            fname: "Trisha",
            lname: "Singh",
            class: 1,
            div: "D",
            rollno: 401,
            gender: F,
            favsports: "Cricket",
            house: "Green",
            bloodgroup: "O+",
            mobile: 948112512,
            city: "Pune",
          },
          {
            fname: "Ramesh",
            lname: "Kumar",
            class: 7,
            div: "C",
            rollno: 321,
            gender: M,
            favsports: "Football",
            house: "Green",
            bloodgroup: "A+",
            mobile: 942412512,
            city: "Mumbai",
          },
          {
            fname: "Zaheer",
            lname: "Khan",
            class: 10,
            div: "A",
            rollno: 41,
            gender: M,
            favsports: "Cricket",
            house: "Green",
            bloodgroup: "B+",
            mobile: 911112000,
            city: "Belgaum",
          },
          {
            fname: "John",
            lname: "Mathew",
            class: 8,
            div: "C",
            rollno: 10,
            gender: M,
            favsports: "Football",
            house: "Purple",
            bloodgroup: "B+",
            mobile: 777777512,
            city: "Pune",
          },
          {
            fname: "Wahid",
            lname: "Shaikh",
            class: 7,
            div: "B",
            rollno: 110,
            gender: M,
            favsports: "Kabbadi",
            house: "orange",
            bloodgroup: "A+",
            mobile: 777552500,
            city: "Nanded",
          },
          {
            fname: "Rishi",
            lname: "Singh",
            class: 8,
            div: "B",
            rollno: 741,
            gender: M,
            favsports: "Football",
            house: "Orange",
            bloodgroup: "A-",
            mobile: 948145512,
            city: "Bangalore",
          },
        ];
        




module.exports=studentsInfo;